# Generated by Django 2.1.3 on 2018-11-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='TeacherID',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Contact',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
